### ISSUE TITLE
Invalid Manifest for org.eclipse.ui.intro

### ISSUE THREAD

**Issue by amergey** [eclipse-platform/eclipse.platform.ua#122]
Since commit [9c6244e0b8e64c2c7fde93836070213ec39335a0](https://github.com/eclipse-platform/eclipse.platform.ua/commit/9c6244e0b8e64c2c7fde93836070213ec39335a0)
org.eclipse.core.expressions is removed but is still necessary (at compile time, and runtime as well)

Now it comes from org.eclipse.help.base (which reexport it)  and without org.eclipse.help.base plugin in target platform, displaying welcome intro is not possible (CNFE for org.eclipse.core.expressions.IEvaluationContext)

I think either org.eclipse.base should become mandatory, either org.eclipse.core.expressions should be restored, otherwise it can leads with broken products

**Comment by iloveeclipse** [comment]
@HannesWell : could sou please check?

**Comment by HannesWell** [comment]
Good catch @amergey, thanks for this report.
Just created https://github.com/eclipse-platform/eclipse.platform.ua/pull/123 to restore the bundle requirement.
Re-exports are really bad on the long run especially when making the re-exporter an optional requirement.

> I think either org.eclipse.base should become mandatory, either org.eclipse.core.expressions should be restored, otherwise it can leads with broken products

Making org.eclipse.help a mandatory required bundle of o.e.ui.intro would definitely have the same effect. From my first look I have the impression that it isn't optional anyway, but I cannot tell for sure if the o.e.ui.intro can reasonable work without the help Plugin.
@amergey do you have more insight in the details, since you encountered this situation?

If you think, o.e.help should become a mandatory requirement would you like to open a PR to apply that fix?

**Comment by laeubi** [comment]
> Re-exports are really bad on the long run especially when making the re-exporter an optional requirement.

Also without optional requirements... re-export is more a way to transition from one exporter to another (something that would be avoided by import-package much better), I even think PDE should warn if a bundle uses a reexported package and suggest to instead use the real exporting bundle (or even better use import-package).
